### ISSUE TITLE
Request for Documentation/Help to use this library

### ISSUE THREAD

**Issue by ssamran15** [lisachenko/php-deal#5]
Hi,

Although I am not an expert in PHP, also new to Design By Contract paradigm. I found this library very useful for DbC. but I could not found a comprehensive guidance or documentation for it. 
My specific question is can I have its comprehensive documentation? 
or at-least some preliminary guidence how I can define my own pre-conditions and post-conditions?
 
In demo files Account.php when I tried to introduce new methods but they did not follow the same pre-conditions that previous methods were following. 

Many Thanks in advance

Samran

**Comment by lisachenko** [comment]
Hello, @ssamran15! Thank you for this request

I will be able to write some documentation about DbC at this weekend, it will include description of each annotation for contracts and special variables, available for checking values.

**Comment by ssamran15** [comment]
Thanks @lisachenko! your effort and prompt response is highly appreciated. looking forward for the documentation of your tremendous work.

**Comment by lisachenko** [comment]
Ready: https://github.com/lisachenko/php-deal/wiki/Quick-reference

**Comment by ssamran15** [comment]
Thanks @lisachenko its really a great help to understand and use this library. I have few questions.
1)- Where are the expression handlers defined or in other words which Class/File is handling the Expressions (@Contract\Verify("$amount>0 && is_numeric($amount)"))
2)- How complex expressions we can specify?
3)- How i can introduce my custom expression handlers?

many thanks in advance
